version: '3.8'
services:
  cache:
    image: redislabs/redisearch:latest
    restart: always
    ports:
      - '6380:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - $PWD/_data:/data
