version: '1'

services:
  nodejs:
    build:
      context: .
      dockerfile: dockerfile
    image: pmeflow_nodejs
    container_name: pmeflow_nodejs
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules: 