#Use latest node image version
FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

#Expose port on 8080 in the docker container
EXPOSE 8080

#Run npm install
CMD [ "npm", "install" ]

#Run those commands to launch the app
CMD [ "npm", "run", "serve" ]
